# Generated by Django 5.0.3 on 2024-04-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(default=' ', max_length=1000),
        ),
    ]
